use std::collections::{BTreeMap, BTreeSet};

use crate::{ItemCategory, JjItem, JjMech, JjTrait, TraitCategory};

const JJ_MIT_NOTICE: &str = r#"# Portions derived from JJ's MechWarrior 5: Mercenaries Save Editor.
# Copyright (c) 2026 JJ (jonayetjubaer-cmyk)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"#;

pub(crate) fn render_item_catalog_py(items: &[JjItem]) -> String {
    let mut weapons = Vec::new();
    let mut equipment = Vec::new();
    let mut ammo = Vec::new();

    for item in items {
        match item.category {
            ItemCategory::Weapon => weapons.push(item),
            ItemCategory::Equipment => equipment.push(item),
            ItemCategory::Ammo => ammo.push(item),
        }
    }

    let mut output = String::new();
    output.push_str("\"\"\"Generated MW5 Mercs inventory item catalog.\n\n");
    output.push_str("Generated by Scarab from scanned MW5 catalog item assets.\n");
    output.push_str("Category -> inventory array:\n");
    output.push_str("  weapon -> WeaponInventory ; equipment & ammo -> EquipmentInventory\n");
    output.push_str("\"\"\"\n");
    push_list(&mut output, "WEAPONS", &weapons);
    push_list(&mut output, "EQUIPMENT", &equipment);
    push_list(&mut output, "AMMO", &ammo);
    output.push_str("CATALOG = {\"weapon\": WEAPONS, \"equipment\": EQUIPMENT, \"ammo\": AMMO}\n");
    output.push_str("CATEGORY_INVENTORY = {\"weapon\": \"weapon\", \"equipment\": \"equipment\", \"ammo\": \"equipment\"}\n");
    output
}

pub(crate) fn render_item_catalog_json(items: &[JjItem]) -> String {
    let weapons = item_rows(
        items
            .iter()
            .filter(|item| item.category == ItemCategory::Weapon),
    );
    let equipment = item_rows(
        items
            .iter()
            .filter(|item| item.category == ItemCategory::Equipment),
    );
    let ammo = item_rows(
        items
            .iter()
            .filter(|item| item.category == ItemCategory::Ammo),
    );
    format!(
        "{}\n",
        serde_json::to_string_pretty(&serde_json::json!({
            "weapons": weapons,
            "equipment": equipment,
            "ammo": ammo,
            "category_inventory": {
                "weapon": "weapon",
                "equipment": "equipment",
                "ammo": "equipment"
            }
        }))
        .expect("catalog JSON serialization should not fail")
    )
}

pub(crate) fn render_mech_catalog_py_with_hero_names(
    mechs: &[JjMech],
    hero_name_overrides: &BTreeMap<String, String>,
) -> String {
    let mut chassis_variants = BTreeMap::<&str, BTreeSet<&str>>::new();
    let mut chassis_tonnage = BTreeMap::<&str, u16>::new();
    let mut hero_names = BTreeMap::<&str, String>::new();
    let known_hero_names = KNOWN_HERO_NAMES.iter().copied().collect::<BTreeMap<_, _>>();
    for mech in mechs {
        chassis_variants
            .entry(&mech.chassis)
            .or_default()
            .insert(&mech.variant);
        if let Some(tons) = mech.tons {
            chassis_tonnage.entry(&mech.chassis).or_insert(tons);
        }
        if mech.is_hero
            && let Some(hero_name) = hero_name_overrides.get(&mech.variant).cloned().or_else(|| {
                known_hero_names
                    .get(mech.variant.as_str())
                    .map(|name| (*name).to_string())
            })
        {
            hero_names.insert(&mech.variant, hero_name);
        }
    }

    let mut output = String::new();
    output.push_str(JJ_MIT_NOTICE);
    output.push_str("\"\"\"Generated MW5 Mercs mech catalog.\n\n");
    output.push_str("Generated by Scarab from scanned MW5 mech data assets.\n");
    output.push_str("\"\"\"\n");
    output.push_str("CHASSIS = {\n");
    for (chassis, variants) in &chassis_variants {
        output.push_str("    ");
        push_python_string(&mut output, chassis);
        output.push_str(": [");
        push_python_string_list(&mut output, variants.iter().copied());
        output.push_str("],\n");
    }
    output.push_str("}\n");
    output.push_str("ALL_VARIANTS = sorted(v for vs in CHASSIS.values() for v in vs)\n");
    output.push_str("DISPLAY_ONLY_VARIANTS = {}\n");
    output.push_str("VARIANT_TO_CHASSIS = {v: name for name, vs in CHASSIS.items() for v in vs}\n");
    output.push_str("VARIANT_TO_CHASSIS.update(DISPLAY_ONLY_VARIANTS)\n");
    output.push_str("HERO_NAMES = {\n");
    for (variant, hero_name) in hero_names {
        output.push_str("    ");
        push_python_string(&mut output, variant);
        output.push_str(": ");
        push_python_string(&mut output, &hero_name);
        output.push_str(",\n");
    }
    output.push_str("}\n");
    output.push_str("CHASSIS_TONNAGE = {\n");
    for (chassis, tons) in &chassis_tonnage {
        output.push_str("    ");
        push_python_string(&mut output, chassis);
        output.push_str(": ");
        output.push_str(&tons.to_string());
        output.push_str(",\n");
    }
    output.push_str("}\n");
    output.push_str(
        r#"
def weight_class(tons) -> str:
    if not tons:
        return ""
    if tons <= 35:
        return "Light"
    if tons <= 55:
        return "Medium"
    if tons <= 75:
        return "Heavy"
    return "Assault"


def chassis_info(name: str):
    chassis = VARIANT_TO_CHASSIS.get(variant_code(name))
    tons = CHASSIS_TONNAGE.get(chassis) if chassis else None
    return (tons, weight_class(tons))


def asset_name(variant: str) -> str:
    return variant if variant.endswith("_MDA") else variant + "_MDA"


def variant_code(name: str) -> str:
    code = name[:-4] if name.endswith("_MDA") else name
    if code.endswith("_PLAYABLE"):
        code = code[:-len("_PLAYABLE")]
    return code


def display(name: str) -> str:
    code = variant_code(name)
    chassis = VARIANT_TO_CHASSIS.get(code)
    if not chassis:
        return code
    hero = HERO_NAMES.get(code)
    if hero:
        return f'{chassis} "{hero}" ({code})'
    return f"{chassis} ({code})"


def _label(name, code):
    hero = HERO_NAMES.get(code)
    return f"{name}  {code}" + (f'  "{hero}"' if hero else "")


LABELED = [(_label(n, v), v) for n in sorted(CHASSIS) for v in sorted(CHASSIS[n])]
"#,
    );
    output
}

pub(crate) fn render_mech_catalog_json_with_hero_names(
    mechs: &[JjMech],
    hero_name_overrides: &BTreeMap<String, String>,
) -> String {
    let mut chassis_variants = BTreeMap::<&str, BTreeSet<&str>>::new();
    let mut chassis_tonnage = BTreeMap::<&str, u16>::new();
    let mut hero_names = BTreeMap::<&str, String>::new();
    let known_hero_names = KNOWN_HERO_NAMES.iter().copied().collect::<BTreeMap<_, _>>();
    for mech in mechs {
        chassis_variants
            .entry(&mech.chassis)
            .or_default()
            .insert(&mech.variant);
        if let Some(tons) = mech.tons {
            chassis_tonnage.entry(&mech.chassis).or_insert(tons);
        }
        if mech.is_hero
            && let Some(hero_name) = hero_name_overrides.get(&mech.variant).cloned().or_else(|| {
                known_hero_names
                    .get(mech.variant.as_str())
                    .map(|name| (*name).to_string())
            })
        {
            hero_names.insert(&mech.variant, hero_name);
        }
    }
    let chassis = chassis_variants
        .into_iter()
        .map(|(chassis, variants)| {
            (
                chassis,
                variants.into_iter().map(str::to_string).collect::<Vec<_>>(),
            )
        })
        .collect::<BTreeMap<_, _>>();
    format!(
        "{}\n",
        serde_json::to_string_pretty(&serde_json::json!({
            "chassis": chassis,
            "all_variants": mechs.iter().map(|mech| mech.variant.as_str()).collect::<BTreeSet<_>>(),
            "display_only_variants": {},
            "hero_names": hero_names,
            "chassis_tonnage": chassis_tonnage
        }))
        .expect("catalog JSON serialization should not fail")
    )
}

pub(crate) fn render_trait_catalog_py(traits: &[JjTrait]) -> String {
    let mut pilot_traits = Vec::new();
    let mut mech_traits = Vec::new();

    for catalog_trait in traits {
        match catalog_trait.category {
            TraitCategory::Pilot => pilot_traits.push(catalog_trait),
            TraitCategory::Mech => mech_traits.push(catalog_trait),
        }
    }

    let mut output = String::new();
    output.push_str(JJ_MIT_NOTICE);
    output.push_str("\"\"\"Generated pilot / mech trait asset-name catalog.\n\n");
    output.push_str("Generated by Scarab from scanned MW5 trait data assets.\n");
    output.push_str(
        "Pilot traits use MWPilotTraitDataAsset; mech traits use MWMechTraitDataAsset.\n",
    );
    output.push_str("\"\"\"\n\n");
    push_trait_list(&mut output, "PILOT_TRAITS", &pilot_traits);
    output.push('\n');
    push_trait_list(&mut output, "MECH_TRAITS", &mech_traits);
    output.push_str(
        r#"
_SEP = " -- "


def display(asset: str, label: str | None = None) -> str:
    """Dropdown display string for a trait: 'Asset -- Friendly Label'."""
    return f"{asset}{_SEP}{label}" if label else asset


def dropdown_values(save_names, catalog) -> list[str]:
    """Merge save-harvested asset names with the generated catalog into sorted
    display strings (catalog entries get their friendly label)."""
    labels = dict(catalog)
    names = set(save_names) | set(labels)
    return sorted((display(n, labels.get(n)) for n in names), key=str.lower)


def resolve(text: str) -> str:
    """A dropdown display string (or raw typed name) -> bare asset name."""
    return text.split(_SEP, 1)[0].strip()
"#,
    );
    output
}

pub(crate) fn render_trait_catalog_json(traits: &[JjTrait]) -> String {
    let pilot_traits = trait_rows(
        traits
            .iter()
            .filter(|catalog_trait| catalog_trait.category == TraitCategory::Pilot),
    );
    let mech_traits = trait_rows(
        traits
            .iter()
            .filter(|catalog_trait| catalog_trait.category == TraitCategory::Mech),
    );
    format!(
        "{}\n",
        serde_json::to_string_pretty(&serde_json::json!({
            "pilot_traits": pilot_traits,
            "mech_traits": mech_traits
        }))
        .expect("catalog JSON serialization should not fail")
    )
}

const KNOWN_HERO_NAMES: &[(&str, &str)] = &[
    ("ANH-IR", "Iron Reckoning"),
    ("ARC-AGC", "Agincourt"),
    ("ARC-T", "Tempest"),
    ("AS7-BH", "Boar's Head"),
    ("AS7-KR", "Kraken"),
    ("ASN-DD", "DarkDeath"),
    ("AWS-PB", "Pretty Baby"),
    ("BJ-A", "Arrow"),
    ("BL-P-KNT", "Partisan"),
    ("BL-P-KNT2", "Partisan"),
    ("BLR-1GHE", "HellSlinger"),
    ("BNC-LM", "La Malinche"),
    ("BNC-SR", "Siren"),
    ("BSW-HR", "High Roller"),
    ("CDA-X5", "The X-5"),
    ("CHP-BF", "Balled Fist"),
    ("CN9-YLW", "Yen-Lo-Wang"),
    ("CN9-YLW2", "Yen-Lo-Wang"),
    ("COM-TDK", "The Death's Knell"),
    ("CP-S", "Sleipnir"),
    ("CPLT-BB", "Butterbee"),
    ("CPLT-J", "Jester"),
    ("CRB-FL", "Florentine"),
    ("CRD-CR", "Crael"),
    ("CTF-IM", "Ilya Muromets"),
    ("DRG-FANG", "Fang"),
    ("DRG-FLAME", "Flame"),
    ("DRG-SDW", "Sidewinder"),
    ("DV-FR", "Frenzy"),
    ("EBJ-EC", "Esprit de Corps"),
    ("ENF-GH", "Ghillie"),
    ("FS9-E", "Ember"),
    ("FS9-FS", "Firestorm"),
    ("GHR-MJ", "Mjölnir"),
    ("GRF-1E", "Sparky"),
    ("GRF-AR", "Ares"),
    ("HBK-AZ", "Azreal"),
    ("HBK-GI", "Grid Iron"),
    ("HCT-MA", "Man-at-Arms"),
    ("HGN-HM", "Heavy Metal"),
    ("HGN-RS", "Redshank"),
    ("HTM-ON", "Onimaru"),
    ("INC-SA", "Sabre"),
    ("JM6-FB", "Firebrand"),
    ("JR7-IIC-FY", "Fury"),
    ("JR7-O", "Oxide"),
    ("JVN-HT", "Hi There!"),
    ("KDK-SB", "Spirit Bear"),
    ("KGC-CAR", "Carapace"),
    ("KGC-KJ", "Kaiju"),
    ("KTO-GB", "Golden Boy"),
    ("LCT-PB", "Pirate's Bane"),
    ("LDK-IDM", "Indomitable"),
    ("LGB-HS", "Hailstorm"),
    ("MAD-AH", "Armageddon's Hammer"),
    ("MAD-BH", "Bounty Hunter"),
    ("MAD-BH2", "Bounty Hunter"),
    ("MAL-KO", "Knockout"),
    ("NTG-JK", "Jade Kite"),
    ("ON1-P", "Protector"),
    ("ON1-YAJ", "Yad al-Jauza"),
    ("PNT-KK", "Katana Kat"),
    ("PXH-KB", "Kobold"),
    ("PXH-KK", "Kuroi Kiri"),
    ("QKD-IV4", "IV-4"),
    ("QKD-SC", "Scrapper"),
    ("RFL-DB", "Dao Breaker"),
    ("RFL-DNA", "Diana"),
    ("RFL-LK", "Legend-Killer"),
    ("RVN-H", "Huginn"),
    ("SDR-A", "Anansi"),
    ("SHD-GD", "Gray Death"),
    ("STK-M", "Misery"),
    ("TBT-LG", "Loup de Guerre"),
    ("TDR-5S-T", "Top Dog"),
    ("UM-K9", "K-9"),
    ("UM-SC", "Street Cleaner"),
    ("VL-BL", "Bloodlust"),
    ("VND-1SIB", "St. Ives' Blues"),
    ("VTR-BSK", "Basilisk"),
    ("VTR-DS", "Dragon Slayer"),
    ("WHM-BW", "Black Widow"),
    ("WLF-GR", "Grinner"),
    ("WVR-Q", "Quarantine"),
    ("ZEU-SK", "Skokomish"),
];

fn push_list(output: &mut String, name: &str, items: &[&JjItem]) {
    output.push_str(name);
    output.push_str(" = [\n");
    for item in items {
        output.push_str("    (");
        push_python_string(output, &item.asset_name);
        output.push_str(", ");
        push_python_string(output, &item.data_asset_type);
        output.push_str("),\n");
    }
    output.push_str("]\n");
}

fn item_rows<'a>(items: impl Iterator<Item = &'a JjItem>) -> Vec<serde_json::Value> {
    items
        .map(|item| {
            serde_json::json!({
                "asset_name": item.asset_name,
                "data_asset_type": item.data_asset_type,
                "category": item.category.as_jj_name()
            })
        })
        .collect()
}

fn trait_rows<'a>(traits: impl Iterator<Item = &'a JjTrait>) -> Vec<serde_json::Value> {
    traits
        .map(|catalog_trait| {
            serde_json::json!({
                "asset_name": catalog_trait.asset_name,
                "friendly_label": catalog_trait.friendly_label
            })
        })
        .collect()
}

fn push_trait_list(output: &mut String, name: &str, traits: &[&JjTrait]) {
    output.push_str(name);
    output.push_str(" = [\n");
    for catalog_trait in traits {
        output.push_str("    (");
        push_python_string(output, &catalog_trait.asset_name);
        output.push_str(", ");
        push_python_string(output, &catalog_trait.friendly_label);
        output.push_str("),\n");
    }
    output.push_str("]\n");
}

fn push_python_string_list<'a>(output: &mut String, values: impl Iterator<Item = &'a str>) {
    let mut first = true;
    for value in values {
        if first {
            first = false;
        } else {
            output.push_str(", ");
        }
        push_python_string(output, value);
    }
}

fn push_python_string(output: &mut String, value: &str) {
    let quote = if value.contains('\'') && !value.contains('"') {
        '"'
    } else {
        '\''
    };

    output.push(quote);
    for character in value.chars() {
        match (character, quote) {
            ('\\', _) => output.push_str("\\\\"),
            ('\'', '\'') => output.push_str("\\'"),
            ('"', '"') => output.push_str("\\\""),
            ('\n', _) => output.push_str("\\n"),
            ('\r', _) => output.push_str("\\r"),
            ('\t', _) => output.push_str("\\t"),
            (character, _) => output.push(character),
        }
    }
    output.push(quote);
}
